//# auto generated by cli

/**
 * @returns {HTMLDivElement}
 * @param selector {string}
 */
const $ = (selector) => document.querySelector(selector);

/**
 * @returns {HTMLDivElement[]}
 * @param selector {string}
 */
const $$ = (selector) => document.querySelectorAll(selector);

/**
 * Determine the mobile operating system.
 * This function returns one of 'iOS', 'Android', 'Windows Phone', or 'unknown'.
 *
 * @returns {String}
 */
function getMobileOperatingSystem() {
	var userAgent = navigator.userAgent || navigator.vendor || window.opera;

	// Windows Phone must come first because its UA also contains "Android"

	if (/android/i.test(userAgent)) {
		return 'Android';
	}

	// iOS detection from: http://stackoverflow.com/a/9039885/177710
	if (/iPad|iPhone|iPod/.test(userAgent) && !window.MSStream) {
		return 'iOS';
	}

	return 'PC';
}

const platform = {
	Android: 'Android',
	iOS: 'iOS',
	PC: 'javascript:void(0);',
};

const dkSlider = new Swiper('.dsList1', {
	loop: true,
	autoplay: {
		delay: 2000,
	},
});

$$('.ptext').forEach(v => {
  const r = Math.floor(Math.random() * 17) + 3;
  v.innerHTML = r + 'ms';
})

function toggleBottomSheet() {
	$('.bottom-sheet').classList.toggle('hidden');
	$('body').classList.toggle('ofh');
}

function closeBottomSheet() {
	$('.close-hd').parentElement.remove();
}

function tvc(v) {
	return ('0' + v).slice(-2);
}

setInterval(() => {
	const now = dayjs();
	const tomorrow = now.add(1, 'day').startOf('day');
	const timeRemaining = tomorrow.diff(now, 'second');
	const hours = tvc(Math.floor(timeRemaining / 3600));
	const minutes = tvc(Math.floor((timeRemaining % 3600) / 60));
	const seconds = tvc(timeRemaining % 60);
	$('#dayLeft').innerHTML = `${hours}:${minutes}:${seconds}`;
}, 1000);

setInterval(() => {
	const now = dayjs();
  const currentDay = now.day();
  const daysUntilMonday = 1 - currentDay;
  const nextMonday = now.add(daysUntilMonday, 'day');
  const timeRemaining = nextMonday.startOf('day').diff(now, 'second');
	const days = Math.floor(timeRemaining / 86400);
	const hours = tvc(Math.floor((timeRemaining % 86400) / 3600));
	const minutes = tvc(Math.floor((timeRemaining % 3600) / 60));
	const seconds = tvc(timeRemaining % 60);
	$('#weekLeft').innerHTML = `<span class="digit">${days}</span> <span style="font-size: 11px; padding: 0 4px">ngày </span><span class="digit">${hours}:${minutes}:${seconds}</span>`;
}, 1000);

setInterval(() => {
	const now = dayjs();
	const nextMonth = now.add(1, 'month');
	const firstDayOfNextMonth = nextMonth.startOf('month');
	const timeRemaining = firstDayOfNextMonth.diff(now, 'second');
	const days = Math.floor(timeRemaining / 86400);
	const hours = tvc(Math.floor((timeRemaining % 86400) / 3600));
	const minutes = tvc(Math.floor((timeRemaining % 3600) / 60));
	const seconds = tvc(timeRemaining % 60);
	$('#monthLeft').innerHTML = `<span class="digit">${days}</span> <span style="font-size: 11px; padding: 0 4px">ngày</span> <span class="digit">${hours}:${minutes}:${seconds}</span>`;
}, 1000);
